# Optimized environment for RTX 40-series GPUs (RTX 4090, 4080, etc.)
# Uses CUDA 12.1 via pip for maximum compatibility with latest NVIDIA drivers
name: neuralhydrology_rtx40
channels:
  - defaults
  - conda-forge
dependencies:
  - bokeh
  - h5py
  - hdf5
  - jupyter
  - matplotlib
  - netcdf4
  - numba
  - pandas
  - geopandas
  - pip
  - pytest
  - pytest-cov
  - python=3.10
  - ruamel.yaml
  - scipy
  - sphinx
  - tqdm
  - xarray
  - yapf
  - pip:
    # PyTorch with CUDA 12.1 support for RTX 40-series compatibility
    - torch==2.5.1+cu121 --index-url https://download.pytorch.org/whl/cu121
    - torchvision==0.20.1+cu121 --index-url https://download.pytorch.org/whl/cu121
    - torchaudio==2.5.1+cu121 --index-url https://download.pytorch.org/whl/cu121
    - tensorboard
    - sphinx-rtd-theme
    - nbsphinx
    - nbsphinx-link
    # Add neuralhydrology in development mode (run 'pip install -e .' after environment creation)
