# Environment for CUDA 12.x systems (NVIDIA driver 535+ / RTX 40-series)
# This configuration uses pip for PyTorch installation to ensure CUDA compatibility
name: neuralhydrology
channels:
  - defaults
  - conda-forge
dependencies:
  - bokeh
  - h5py
  - hdf5
  - jupyter
  - matplotlib
  - netcdf4
  - numba
  - pandas
  - pip
  - pytest
  - pytest-cov
  - python=3.10
  - ruamel.yaml
  - scipy
  - sphinx
  - tqdm
  - xarray
  - yapf
  - pip:
    # Install PyTorch with CUDA 12.1 support via pip for better compatibility
    - torch==2.5.1+cu121 --index-url https://download.pytorch.org/whl/cu121
    - torchvision==0.20.1+cu121 --index-url https://download.pytorch.org/whl/cu121
    - torchaudio==2.5.1+cu121 --index-url https://download.pytorch.org/whl/cu121
    - tensorboard
    - sphinx-rtd-theme
    - nbsphinx
    - nbsphinx-link
