# GPU environment for NVIDIA GPUs with CUDA support
# Compatible with modern NVIDIA GPUs (RTX 20/30/40 series, Tesla, etc.)
# Requires NVIDIA drivers version 450+ and CUDA 11.8+
name: neuralhydrology
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - bokeh
  - h5py
  - hdf5
  - jupyter
  - matplotlib
  - netcdf4
  - numba
  - pandas
  - pip
  - pytest
  - pytest-cov
  - python=3.12
  - pytorch
  - pytorch-cuda=11.8
  - torchvision
  - torchaudio
  - ruamel.yaml
  - scipy
  - sphinx
  - tqdm
  - xarray
  - yapf
  - pip:
    - tensorboard
    - sphinx-rtd-theme
    - nbsphinx
    - nbsphinx-link
