# Environment for CUDA 11.8 systems (older NVIDIA drivers / RTX 30-series and below)
# Use this for systems with NVIDIA drivers < 535 or if CUDA 12 causes issues
name: neuralhydrology
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - bokeh
  - h5py
  - hdf5
  - jupyter
  - matplotlib
  - netcdf4
  - numba
  - pandas
  - pip
  - pytest
  - pytest-cov
  - python=3.10  # Changed from 3.12 to 3.10 for better compatibility
  - pytorch
  - pytorch-cuda=11.8
  - ruamel.yaml
  - scipy
  - sphinx
  - tqdm
  - xarray
  - yapf
  - pip:
    - tensorboard
    - sphinx-rtd-theme
    - nbsphinx
    - nbsphinx-link